# Generated by Django 3.0.6 on 2020-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
