# Generated by Django 3.0.5 on 2020-05-12 23:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(7)])),
                ('home_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(3)])),
                ('additional_info', models.CharField(blank=True, max_length=999)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(16)])),
                ('card_year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032')], default=1)),
                ('card_month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1)),
                ('card_CVC', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(3)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField()),
                ('cart', models.ManyToManyField(to='cart.Cart')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ContactInformation')),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
